# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Setup
title:            gebinabi
description:      ''
url:              http://gebinabi.github.io
baseurl:          /

paginate:         5
