# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Setup
title:            gebinabi
description:      'page of gebinabi'
url:              http://gebinabi.github.io
baseurl:          /

paginate:         5

# Custom vars

remote_theme : poole/hyde

author_github:
  repo:           https://github.com/poole/hyde
